"""The buyer brief: one page, one row per company, for whoever works the leads.

`leads.csv` is the handover for a spreadsheet. This is the same material for a
person reading it once: recent buyers from the sources outreach may use,
grouped by company, strongest first, each linked to its own advert. The
Reddit hiring rooms are listed apart, because their records wait on the
access decision (docs/scope-and-access.md, section 6).

It was built by hand from a script outside the repo until 2026-09-29, which
meant it could not be regenerated by anyone else, or on a schedule, and was one
temp-folder cleanup away from being lost. It is generated here, from the
archive, like everything else a reviewer reads.

No contact details are collected into it. The advert link is the route, and
who gets contacted is decided by a person; nothing is sent from here.
"""
from __future__ import annotations

import json
import re
from importlib import resources
import sqlite3
from datetime import datetime, timedelta, timezone
from pathlib import Path

from . import OUTCOMES, TABLE, outcomes
from .leads import MAX_AGE_DAYS, too_old

TEMPLATE = "brief_template.html"   # shipped beside this module

#: The sources outreach may use, and how the page names them. Forum records
#: can be buyers too (an owner describing work they would pay to remove), so
#: they are listed; Reddit rooms are not in this map on purpose.
SOURCE_LABEL = {
    "hn/hiring": "HN Who is hiring", "himalayas/contract": "Himalayas",
    "remotive/jobs": "Remotive", "jobicy/jobs": "Jobicy",
    "hn/comment": "HN comment", "hn/ask": "Ask HN", "hn/show": "Show HN", "hn/story": "HN story",
}

# `(?<!\d)\d{1,6}` rather than `\d+`: an unbounded run before an optional
# space backtracks on long digit strings.
_RATE = re.compile(r"(\$|€|£|\busd\b|\beur\b|\bgbp\b|/hr|/hour|per hour|hourly|/mo\b"
                   r"|(?<!\d)\d{1,6} ?k\b|hrs?/w)", re.I)
_URLISH = re.compile(r"(?:^(?:https?://|www\.))|(?:\.(?:com|io|ai|xyz|fr|dev|co)/?$)", re.I)
_PLACE = re.compile(r"(remote|onsite|on-site|hybrid|\b[A-Z][a-z]+,? [A-Z]{2}\b|london|berlin|new york"
                    r"|nyc|sf\b|san francisco|europe|us only|emea|latam)", re.I)
_CONTRACT = re.compile(r"contract|fractional|freelance|part[- ]time|consult", re.I)
_MATCHED = re.compile(r"\[matched: ([^\]]*)\]")
#: An agency hiring contractors for its OWN client projects says so in the
#: plural. It is kept -- it may buy white-label engineering -- but marked, so
#: nobody mistakes it for the company with the problem. (The singular, "our
#: client is ...", is a recruiter and is rejected by the hiring rules.)
_AGENCY = re.compile(r"(?<!\w)for (our|its) (\w+ ){0,2}clients(?!\w)", re.I)
#: Reddit posts that still read like a data task or name no engineering work.
_REDDIT_TASK = re.compile(r"get paid|role-play|contributor|annotat|data (label|collection)|generalist"
                          r"|per ?task|remote ai freelance|specialists?\b|writers?\b", re.I)
_REDDIT_ENGINEERING = re.compile(r"engineer|developer|software|full-?stack|python|\bapp\b|\bqa\b"
                                 r"|technical|data scientist|tech partner", re.I)


def _segments(title: str) -> list:
    return [s.strip() for s in (title or "").split("|") if s.strip()]


def _pick(segs, pattern, skip=()):
    for s in segs[1:]:
        if s not in skip and pattern.search(s):
            return s[:60]
    return ""


def _why(row) -> list:
    m = _MATCHED.search(row["match_reason"] or "")
    return [w.strip() for w in (m.group(1) if m else "").split(",") if w.strip()][:6]


def _stage(outcome: str) -> int:
    return OUTCOMES.index(outcome) if outcome in OUTCOMES else 0


def _role(best: dict, segs: list, company: str) -> str:
    """The role, read off the headline's segments; a forum post has only a title."""
    if not company:
        return (best["title"] or "")[:110]
    if len(segs) < 2:
        return ""
    return next((s for s in segs[1:] if not _URLISH.search(s) and not _PLACE.match(s)
                 and not _RATE.search(s[:12])), "")[:90]


def _furthest_outcome(records: list) -> str:
    return max((x["outcome"] or "" for x in records), key=_stage)


def _is_agency(records: list) -> bool:
    return any(_AGENCY.search(f"{x['title'] or ''} {x['excerpt'] or ''}") for x in records)


def _company_row(records: list) -> dict:
    """One row for a company: its strongest advert, and what came of any of them."""
    from .sources.jobboards import _is_gig_task, _is_marketplace
    records.sort(key=lambda x: (-float(x["match_confidence"] or 0), x["created_utc"] or ""))
    best = records[0]
    segs = _segments(best["title"])
    named = best["company"] or ""
    company = "" if named in ("", "unknown") else named
    role = _role(best, segs, company)
    rate = _pick(segs, _RATE)
    intent = best["buyer_intent"] or ""
    engagement = "" if intent == "unknown" else intent
    dates = sorted((x["created_utc"] or "")[:10] for x in records if x["created_utc"])
    return {
        "company": company or "(no company named)",
        "role": role,
        "engagement": engagement,
        "rate": rate,
        "place": _pick(segs, _PLACE, skip=(rate, role)),
        "fit": round(float(best["match_confidence"] or 0), 2),
        "ambiguous": "ambiguous" in (best["match_reason"] or ""),
        "contract": bool(_CONTRACT.search(f"{engagement} {best['title'] or ''}")),
        "agency": _is_agency(records),
        "gig": _is_marketplace(company) or _is_gig_task(best["title"] or ""),
        "source": SOURCE_LABEL.get(best["community"], best["community"]),
        "posted": dates[-1] if dates else "",
        "times": len(records),
        "url": best["source_url"],
        "why": _why(best),
        "outcome": _furthest_outcome(records),
    }


def _split(rows: list, max_age_days: int, now: datetime):
    """Recent buyers from usable sources, the Reddit rooms set apart, and how
    many usable-source adverts were too old to list."""
    recent, reddit, older = [], [], 0
    for r in rows:
        if r["community"].startswith("r/"):
            reddit.append(r)
        elif r["community"] not in SOURCE_LABEL:
            continue
        elif too_old(r, max_age_days, now=now):
            older += 1
        else:
            recent.append(r)
    return recent, reddit, older


def _companies(recent: list) -> list:
    """One row per company; a record that names none is its own row."""
    groups: dict = {}
    for r in recent:
        key = (r["company"] or "").strip().lower()
        groups.setdefault(key if key not in ("", "unknown") else r["record_id"], []).append(r)
    # Strongest first; among equals, contract-shaped first, then newest. Two
    # stable sorts, because "newest" runs the other way from the rest.
    rows = sorted((_company_row(rs) for rs in groups.values()),
                  key=lambda c: c["posted"], reverse=True)
    rows.sort(key=lambda c: (-c["fit"], not c["contract"]))
    return rows


def _reddit_posts(reddit: list) -> list:
    """The set-apart Reddit posts, one per headline, gig-like ones last."""
    posts: dict = {}
    for r in reddit:
        key = (r["title"] or "").strip().lower()[:80] or r["record_id"]
        fit = round(float(r["match_confidence"] or 0), 2)
        if key in posts and posts[key]["fit"] >= fit:
            continue
        title = (r["title"] or "")[:120]
        posts[key] = {"community": r["community"], "title": title, "fit": fit,
                      "url": r["source_url"], "posted": (r["created_utc"] or "")[:10],
                      "gig": bool(_REDDIT_TASK.search(title)) or not _REDDIT_ENGINEERING.search(title)}
    return sorted(posts.values(), key=lambda x: (x["gig"], -x["fit"]))


def build(db: sqlite3.Connection, *, mode: str = "live", max_age_days: int = MAX_AGE_DAYS,
          now: datetime | None = None) -> dict:
    """The brief's data, read off the archive."""
    now = now or datetime.now(timezone.utc)
    rows = [dict(r) for r in db.execute(
        "SELECT record_id, community, company, buyer_intent, title, excerpt, match_confidence, "
        "match_reason, created_utc, source_url, COALESCE(outcome, '') AS outcome "
        f"FROM {TABLE} WHERE mode = ? AND audience = 'buyer' AND COALESCE(removed_utc, '') = ''",
        (mode,))]
    recent, reddit, older = _split(rows, max_age_days, now)
    o = outcomes(db, mode=mode)
    return {
        "generated": now.strftime("%Y-%m-%d"),
        "cutoff": (now - timedelta(days=max_age_days)).strftime("%Y-%m-%d"),
        "max_age_days": max_age_days,
        "total_buyers": len(rows),
        "companies": _companies(recent),
        "older_count": older,
        "reddit_records": len(reddit),
        "reddit": _reddit_posts(reddit),
        "worked": o["worked"],
        "picked": o["picked"],
    }


def render(data: dict) -> str:
    """The page, with the data embedded -- one file that opens anywhere."""
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    page = resources.files(__package__).joinpath(TEMPLATE).read_text(encoding="utf-8")
    return page.replace("/*DATA*/null", payload)


def write(db: sqlite3.Connection, out_dir: str | Path, **kw) -> dict:
    data = build(db, **kw)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    page = out / "buyer-brief.html"
    with open(page, "w", encoding="utf-8") as fh:
        fh.write(render(data))
    with open(out / "brief.json", "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=1)
    return {"path": str(page), "companies": len(data["companies"]),
            "reddit": len(data["reddit"]), "total_buyers": data["total_buyers"],
            "older": data["older_count"], "picked": data["picked"], "worked": data["worked"]}
